import Sidebar from "@/app/mentee/[components]/Sidebar";
import Navbar from "@/app/mentee/[components]/Navbar";

export const metadata = {
  title: "Mentor dashbord",
  description: "Generated by create next app",
};

export default function DachbordLayout({ children }) {
  return (
        <div className="flex gap-[30px] bg-gray-100">
          <div className="max-sm:hidden">
            <Sidebar />
          </div>
          <div className="flex flex-col mr-[12px] w-full">
            <Navbar />
            <div className="h-[90vh] overflow-x-auto overflow-y-auto">
              {children}
            </div>
          </div>
        </div>
  );
}
